### PR TITLE
sdm845: Block core Google apps on the kernel-level

### PR DESCRIPTION
**Pull request by loudsteel**
It is well known that Google has disgusting data collection and is quite
aggressive about it. The best thing to do is to stop it from executing
entirely. This code prevents userspace applications from using linux syscalls
to spawn a new process for core google apps which results in core google apps
seemingly freezing due to android (likely SystemUI) not knowing the processes
have gone away. The user will report this as being "My core google apps froze!"
- Too bad!

### CODE REVIEW

**Comment by loudsteel** [comment]
@AnierinBliss merge plz

**Comment by loudsteel** [comment]
@AnierinBliss Do I need to write a bot to remind you merge thiz every five minutes?

**Comment by loudsteel** [comment]
@AnierinBliss I'm not a tiktok or wechat user, I just want to make your privacy protection stronger.

**Comment by loudsteel** [comment]
@AnierinBliss I know you are online, I'm monitoring your telegram group and watching you send shit to your users.

**Comment by loudsteel** [comment]
@AnierinBliss Also don't forget your promise lmao
https://t.me/EvolutionXOnePlus/61769

**Comment by AnierinBliss** [comment]
Keep the comments coming guys, love the support.

**Comment by loudsteel** [comment]
@AnierinBliss Isn't that you want to protect privacy for your users?

**Comment by loudsteel** [comment]
MERGE IT, RIGHT NOW!

**Comment by loudsteel** [comment]
@AnierinBliss I know you are online, merge thiz ASAP

**Comment by wildlyremix** [comment]
@AnierinBliss reopen thiz

**Pull request closed without merging**
